name: flutter_template
description: "A new Flutter project."
publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^5.0.2
  cloud_functions: ^5.0.2
  collection: ^1.18.0
  cupertino_icons: ^1.0.6
  easy_localization: ^3.0.3
  firebase_analytics: ^11.1.0
  firebase_auth: ^5.1.1
  firebase_core: ^3.1.1
  firebase_messaging: ^15.0.2
  flutter_bloc: ^8.1.6
  flutter_hooks: ^0.20.4
  font_awesome_flutter: ^10.7.0
  freezed_annotation: ^2.4.1
  go_router: ^14.2.0
  google_fonts: ^4.0.4
  json_annotation: ^4.8.1
  responsive_builder: ^0.7.0
  scroll_to_index: ^3.0.1
  smooth_page_indicator: ^1.1.0
  url_launcher: ^6.2.4
  equatable: ^2.0.5
  email_validator: ^3.0.0
  permission_handler: ^11.3.1
  get_it: ^7.7.0
  gap: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.8
  flutter_lints: ^4.0.0
  freezed: ^2.4.6
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/translations/
    - assets/google_fonts/nunito/
    - assets/google_fonts/open_sans/
